# Generated by Django 4.2.7 on 2025-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(default='PLACEHOLDER', max_length=255),
            preserve_default=False,
        ),
    ]
